#!/usr/bin/env bash
set -euo pipefail

if [[ "$#" -ne 3 ]]; then
  echo "usage: $0 <app-bundle> <dmg> <entitlements-plist>" >&2
  exit 2
fi

app_bundle="$1"
dmg_path="$2"
entitlements_path="$3"

for path in "$app_bundle" "$dmg_path" "$entitlements_path"; do
  if [[ ! -e "$path" ]]; then
    echo "::error::Required signing input does not exist: $path" >&2
    exit 1
  fi
done

required=(
  APPLE_CERTIFICATE_BASE64
  APPLE_CERTIFICATE_PASSWORD
  APPLE_SIGNING_IDENTITY
  APPLE_TEAM_ID
  APPLE_API_KEY_BASE64
  APPLE_API_KEY_ID
  APPLE_API_ISSUER_ID
)
missing=()
for name in "${required[@]}"; do
  if [[ -z "${!name:-}" ]]; then
    missing+=("$name")
  fi
done
if [[ ${#missing[@]} -gt 0 ]]; then
  echo "::error::Missing Apple signing credentials: ${missing[*]}" >&2
  exit 1
fi

temp_root="${RUNNER_TEMP:-/tmp}/buzz-apple-signing-${RANDOM}-${RANDOM}"
keychain_path="${temp_root}.keychain-db"
keychain_password="$(uuidgen)"
certificate_path="${temp_root}.p12"
api_key_path="${temp_root}.p8"
rw_dmg_base="${temp_root}-rw"
rw_dmg_path="${rw_dmg_base}.dmg"
signed_dmg_base="${temp_root}-signed"
signed_dmg_path="${signed_dmg_base}.dmg"
app_notary_zip="${temp_root}-app.zip"
mount_path="$(mktemp -d "${RUNNER_TEMP:-/tmp}/buzz-dmg-mount.XXXXXX")"
mounted=false

cleanup() {
  set +e
  if [[ "$mounted" == true ]]; then
    hdiutil detach "$mount_path" -quiet
  fi
  rm -rf "$mount_path" "$keychain_path" "$certificate_path" "$api_key_path" \
    "$rw_dmg_path" "$signed_dmg_path" "$app_notary_zip"
}
trap cleanup EXIT

submit_for_notarization() {
  xcrun notarytool submit "$1" --key "$api_key_path" \
    --key-id "$APPLE_API_KEY_ID" --issuer "$APPLE_API_ISSUER_ID" --wait
}

# macOS uses BSD base64, whose decode flag is -D. Keep decoded credential files
# in the runner's temporary directory and remove them via the trap above.
printf '%s' "$APPLE_CERTIFICATE_BASE64" | base64 -D > "$certificate_path"
printf '%s' "$APPLE_API_KEY_BASE64" | base64 -D > "$api_key_path"
chmod 600 "$certificate_path" "$api_key_path"

security create-keychain -p "$keychain_password" "$keychain_path"
security set-keychain-settings -lut 21600 "$keychain_path"
security unlock-keychain -p "$keychain_password" "$keychain_path"
security import "$certificate_path" -k "$keychain_path" -P "$APPLE_CERTIFICATE_PASSWORD" \
  -T /usr/bin/codesign -T /usr/bin/security
security set-key-partition-list -S apple-tool:,apple:,codesign: -s \
  -k "$keychain_password" "$keychain_path"

# Sign the final app bundle with hardened runtime. The app-level entitlements
# must be applied only to the outer bundle; --deep signs nested frameworks and
# sidecars without copying those entitlements into their individual signatures.
codesign --force --deep --options runtime --timestamp --keychain "$keychain_path" \
  --sign "$APPLE_SIGNING_IDENTITY" --entitlements "$entitlements_path" "$app_bundle"
codesign --verify --deep --strict --verbose=2 "$app_bundle"

actual_team_id="$(codesign -dvvv "$app_bundle" 2>&1 | sed -n 's/^TeamIdentifier=//p' | head -1)"
if [[ "$actual_team_id" != "$APPLE_TEAM_ID" ]]; then
  echo "::error::Signing certificate team '$actual_team_id' does not match APPLE_TEAM_ID" >&2
  exit 1
fi

# The updater delivers the tarball, not the DMG. Notarize and staple the app
# itself before it is packaged so an offline Gatekeeper assessment succeeds
# after an in-app update as well as after an initial DMG installation.
ditto -c -k --keepParent "$app_bundle" "$app_notary_zip"
submit_for_notarization "$app_notary_zip"
xcrun stapler staple "$app_bundle"
xcrun stapler validate "$app_bundle"

# Preserve the Finder layout/background generated by Tauri. A compressed DMG is
# read-only, so replace the app in a temporary writable image, then recompress.
hdiutil convert "$dmg_path" -format UDRW -o "$rw_dmg_base"
hdiutil attach "$rw_dmg_path" -readwrite -noverify -noautoopen \
  -mountpoint "$mount_path" >/dev/null
mounted=true
rm -rf "$mount_path/Buzz.app"
ditto "$app_bundle" "$mount_path/Buzz.app"
hdiutil detach "$mount_path" -quiet
mounted=false
hdiutil convert "$rw_dmg_path" -format UDZO -o "$signed_dmg_base"
mv "$signed_dmg_path" "$dmg_path"

submit_for_notarization "$dmg_path"
xcrun stapler staple "$dmg_path"
xcrun stapler validate "$dmg_path"
